#
# Makefile for breath led devices
#

ifeq ($(CONFIG_MACH_FIND7),y)
obj-$(CONFIG_SN3193_SLED)		+= shineled_driver_find7.o
endif
ifeq ($(CONFIG_MACH_FIND7OP),y)
obj-$(CONFIG_SN3193_SLED)		+= shineled_driver_find7op.o
endif
